---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: my-bluefin
description: This is my personal OS image.

base-image: ghcr.io/hagenest/bluefin-infinitybook-gen10
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
    install:
      packages:
    remove:
      packages:


  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox

  - type: signing
