---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: my-bluefin
description: This is my personal OS image.

base-image: ghcr.io/hagenest/bluefin-infinitybook-gen10
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - tealdeer

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - io.gitlab.librewolf-community
          - io.github.ungoogled_software.ungoogled_chromium
          - dev.zed.Zed
          - io.github.alainm23.planify
          - com.valvesoftware.Steam
          - dev.vencord.Vesktop
          - im.riot.Riot
          - org.signal.Signal
          - io.github.astralvixen.geforce-infinity
          - org.prismlauncher.PrismLauncher
          - dev.deedles.Trayscale
          - org.gnome.World.PikaBackup
        remove:
          - org.gnome.baobab
          - org.gnome.clocks
          - org.gnome.Maps
          - org.gnome.DejaDup
          - org.gnome.Characters
          - org.gnome.TextEditor

  - type: chezmoi
    repository: "https://github.com/hagenest/dotfiles"
    file-conflict-policy: replace

  - type: gnome-extensions
    install:
      - AppIndicator and KStatusNotifierItem Support
      - Caffeine
      - Network Stats
      - Tiling Shell
      - Just Perfection
    remove:
      - GSConnect

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
        - Inter

  - type: signing
